"""Nâng cấp Document model hỗ trợ Paper và Dataset

Revision ID: 05341442cd18
Revises: 348c943d2330
Create Date: 2026-04-10 08:45:06.214584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05341442cd18'
down_revision = '348c943d2330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('main_file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('external_link', sa.String(length=500), nullable=True))
        batch_op.drop_column('abstract')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('external_link')
        batch_op.drop_column('attachments')
        batch_op.drop_column('main_file_url')
        batch_op.drop_column('description')
        batch_op.drop_column('doc_type')

    # ### end Alembic commands ###
