"""add citation column to papers table

Revision ID: 7c4a6f5865be
Revises: b1769c9cde9b
Create Date: 2026-04-30 16:28:15.408269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4a6f5865be'
down_revision = 'b1769c9cde9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('citation')

    # ### end Alembic commands ###
