"""Add auth fields

Revision ID: 7d9352e3475d
Revises: f19f7e57c7d5
Create Date: 2026-04-06 01:15:08.129076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9352e3475d'
down_revision = 'f19f7e57c7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_login', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('reset_otp')
        batch_op.drop_column('is_first_login')

    # ### end Alembic commands ###
