"""add ai_summary column

Revision ID: b1769c9cde9b
Revises: 9270f2778793
Create Date: 2026-04-29 16:12:51.771174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1769c9cde9b'
down_revision = '9270f2778793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
