"""Rename otp to token

Revision ID: dba82945e2e2
Revises: 7d9352e3475d
Create Date: 2026-04-06 01:26:53.534192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba82945e2e2'
down_revision = '7d9352e3475d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.drop_column('reset_otp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
